const stands = [
 "Star Platinum",
  "The World",
  "Crazy Diamond",
  "Killer Queen",
  "Gold Experience",
  "Sticky Fingers",
  "Stone Free",
  "Tusk Act 4",
  "Made in Heaven",
  "King Crimson",
  "Weather Report",
  "The Hand",
  "Harvest",
  "Hierophant Green",
  "Green Tea",
  "Hermit Purple",
  "Magician's Red",
  "Silver Chariot",
  "The Fool",
  "Emperor",
  "Justice",
  "Lovers",
  "Sun",
  "Death Thirteen",
  "Judgement",
  "High Priestess",
  "Geb",
  "Ebony Devil",
  "Yellow Temperance",
  "Hanged Man",
  "Wheel of Fortune",
  "Dark Blue Moon",
  "Strength",
  "The Lovers",
  "The Sun",
  "Death Thirteen",
  "Judgement",
  "High Priestess",
  "Geb",
  "Crazy Diamond",
  "The Hand",
  "Echoes",
  "Heaven's Door",
  "Aqua Necklace",
  "Bad Company",
  "Red Hot Chili Pepper",
  "The Lock",
  "Surface",
  "Love Deluxe",
  "Pearl Jam",
  "Achtung Baby",
  "Ratt",
  "Harvest",
  "Cinderella",
  "Atom Heart Father",
  "Boy II Man",
  "Earth Wind and Fire",
  "Highway Star",
  "Stray Cat",
  "Super Fly",
  "Gold Experience",
  "Sticky Fingers",
  "Moody Blues",
  "Sex Pistols",
  "Aerosmith",
  "Purple Haze",
  "Spice Girl",
  "Silver Chariot",
  "Chariot Requiem",
  "Gold Experience Requiem",
  "Echoes",
  "Black Sabbath",
  "Soft Machine",
  "Kraft Work",
  "Little Feet",
  "Man in the Mirror",
  "Mr.President",
  "The Grateful Dead",
  "Beach Boy",
  "Baby Face",
  "White Album",
  "Clash",
  "Notorious B.I.G.",
  "Soft Machine",
  "Kraft Work",
  "Mr. President",
  "Silver Chariot",
  "Rolling Stones",
  "The Rolling Stones",
  "Star Platinum",
  "The World",
  "Crazy Diamond",
  "Killer Queen",
  "Gold Experience",
  "Sticky Fingers",
  "Stone Free",
  "Tusk Act 4",
  "Made in Heaven",
  "King Crimson",
  "Weather Report",
  "The Hand",
  "Harvest",
  "Hierophant Green",
  "Green Tea",
  "Hermit Purple",
  "Magician's Red",
  "Silver Chariot",
  "The Fool",
  "Emperor",
  "Justice",
  "Lovers",
  "Sun",
  "Death Thirteen",
  "Judgement",
  "High Priestess",
  "Geb",
  "Ebony Devil",
  "Yellow Temperance",
  "Hanged Man",
  "Wheel of Fortune",
  "Dark Blue Moon",
  "Strength",
  "The Lovers",
  "The Sun",
  "Death Thirteen",
  "Judgement",
  "High Priestess",
  "Geb",
  "Crazy Diamond",
  "The Hand",
  "Echoes",
  "Heaven's Door",
  "Aqua Necklace",
  "Bad Company",
  "Red Hot Chili Pepper",
  "The Lock",
  "Surface",
  "Love Deluxe",
  "Pearl Jam",
  "Achtung Baby",
  "Ratt",
  "Harvest",
  "Cinderella",
  "Atom Heart Father",
  "Boy II Man",
  "Earth Wind and Fire",
  "Highway Star",
  "Stray Cat",
  "Super Fly",
  "Gold Experience",
  "Sticky Fingers",
  "Moody Blues",
  "Sex Pistols",
  "Aerosmith",
  "Purple Haze",
  "Spice Girl",
  "Silver Chariot",
  "Chariot Requiem",
  "Gold Experience Requiem",
  "Echoes",
  "Black Sabbath",
  "Soft Machine",
  "Kraft Work",
  "Little Feet",
  "Man in the Mirror",
  "Mr.President",
  "The Grateful Dead",
  "Beach Boy",
  "Baby Face",
  "White Album",
  "Clash",
  "Notorious B.I.G.",
  "Soft Machine",
  "Kraft Work",
  "Mr. President",
  "Silver Chariot",
  "Rolling Stones",
  "The Rolling Stones",
  "Star Platinum",
  "The World",
  "Crazy Diamond",
  "Killer Queen",
  "Gold Experience",
  "Sticky Fingers",
  "Stone Free",
  "Tusk Act 4",
  "Made in Heaven",
  "King Crimson",
  "Weather Report",
  "The Hand",
  "Harvest",
  "Hierophant Green",
  "Green Tea",
  "Hermit Purple",
  "Magician's Red",
  "Silver Chariot",
  "The Fool",
  "Emperor",
  "Justice",
  "Lovers",
  "Sun",
  "Death Thirteen",
  "Judgement",
  "High Priestess",
  "Geb",
  "Ebony Devil",
  "Yellow Temperance",
  "Hanged Man",
  "Wheel of Fortune",
  "Dark Blue Moon",
  "Strength",
  "The Lovers",
  "The Sun",
  "Death Thirteen",
  "Judgement",
  "High Priestess",
  "Geb",
  "Crazy Diamond",
  "The Hand",
  "Echoes",
  "Heaven's Door",
  "Aqua Necklace",
  "Bad Company",
  "Red Hot Chili Pepper",
  "The Lock",
  "Surface",
  "Love Deluxe",
  "Pearl Jam",
  "Achtung Baby",
  "Ratt",
  "Harvest",
  "Cinderella",
  "Atom Heart Father",
  "Boy II Man",
  "Earth Wind and Fire",
  "Highway Star",
  "Stray Cat",
  "Super Fly",
  "Gold Experience",
  "Sticky Fingers",
  "Moody Blues",
  "Sex Pistols",
  "Aerosmith",
  "Purple Haze",
  "Spice Girl",
  "Silver Chariot",
  "Chariot Requiem",
  "Gold Experience Requiem",
  "Echoes",
  "Black Sabbath",
  "Soft Machine",
  "Kraft Work",
  "Little Feet",
  "Man in the Mirror",
  "Mr.President",
  "The Grateful Dead",
  "Beach Boy",
  "Baby Face",
  "White Album",
  "Clash",
  "Notorious B.I.G.",
  "Soft Machine",
  "Kraft Work",
  "Mr. President",
  "Silver Chariot",
  "Rolling Stones",
  "The Rolling Stones",
  "Star Platinum",
  "The World",
  "Crazy Diamond",
  "Killer Queen",
  "Gold Experience",
  "Sticky Fingers",
  "Stone Free",
  "Tusk Act 4",
  "Made in Heaven",
  "King Crimson",
  "Weather Report",
  "The Hand",
  "Harvest",
  "Hierophant Green",
  "Green Tea",
  "Hermit Purple",
  "Magician's Red",
  "Silver Chariot",
  "The Fool",
  "Emperor",
  "Justice",
  "Lovers",
  "Sun",
  "Death Thirteen",
  "Judgement",
  "High Priestess",
  "Geb",
  "Ebony Devil",
  "Yellow Temperance",
  "Hanged Man",
  "Wheel of Fortune",
  "Dark Blue Moon",
  "Strength",
  "The Lovers",
  "The Sun",
  "Death Thirteen",
  "Judgement",
  "High Priestess",
  "Geb",
  "Crazy Diamond",
  "The Hand",
  "Echoes",
  "Heaven's Door",
  "Aqua Necklace",
  "Bad Company",
  "Red Hot Chili Pepper",
  "The Lock",
  "Surface",
  "Love Deluxe",
  "Pearl Jam",
  "Achtung Baby",
  "Ratt",
  "Harvest",
  "Cinderella",
  "Atom Heart Father",
  "Boy II Man",
  "Earth Wind and Fire",
  "Highway Star",
  "Stray Cat",
  "Super Fly",
  "Gold Experience",
  "Sticky Fingers",
  "Moody Blues",
  "Sex Pistols",
  "Aerosmith",
  "Purple Haze",
  "Spice Girl",
  "Silver Chariot",
  "Chariot Requiem",
  "Gold Experience Requiem",
  "Echoes",
  "Black Sabbath",
  "Soft Machine",
  "Kraft Work",
  "Little Feet",
  "Man in the Mirror",
  "Mr.President",
  "The Grateful Dead",
  "Beach Boy",
  "Baby Face",
  "White Album",
  "Clash",
  "Notorious B.I.G.",
  "Soft Machine",
  "Kraft Work",
  "Mr. President",
  "Silver Chariot",
  "Rolling Stones",
  "The Rolling Stones",
  "Star Platinum",
  "The World",
  "Crazy Diamond",
  "Killer Queen",
  "Gold Experience",
  "Sticky Fingers",
  "Stone Free",
  "Tusk Act 4",
  "Made in Heaven",
  "King Crimson",
  "Weather Report",
  "The Hand",
  "Harvest",
  "Hierophant Green",
  "Green Tea",
  "Hermit Purple",
  "Magician's Red",
  "Silver Chariot",
  "The Fool",
  "Emperor",
  "Justice",
  "Lovers",
  "Sun",
  "Death Thirteen",
  "Judgement",
  "High Priestess",
  "Geb",
  "Ebony Devil",
  "Yellow Temperance",
  "Hanged Man",
  "Wheel of Fortune",
  "Dark Blue Moon",
  "Strength",
  "The Lovers",
  "The Sun",
  "Death Thirteen",
  "Judgement",
  "High Priestess",
  "Geb",
  "Crazy Diamond",
  "The Hand",
  "Echoes",
  "Heaven's Door",
  "Aqua Necklace",
  "Bad Company",
  "Red Hot Chili Pepper",
  "The Lock",
  "Surface",
  "Love Deluxe",
  "Pearl Jam",
  "Achtung Baby",
  "Ratt",
  "Harvest",
  "Cinderella",
  "Atom Heart Father",

];

document.getElementById("findStandBtn").addEventListener("click", function() {
  const randomStand = stands[Math.floor(Math.random() * stands.length)];
  document.getElementById("standResult").textContent = `Your Stand is: ${randomStand}!`;
});
